---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ops-eng-reports
  title: Operations Engineering Reports
  description: Reporting site for Operations Engineering team
spec:
  owner: group:operations-engineering
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ops-eng-reports-frontend
  title: Operations Engineering Reports Frontend
  description: Frontend application for Operations Engineering Reports
  links:
  - url: https://github.com/ministryofjustice/operations-engineering-reports/blob/main/kubernetes_deployment/live/deployment.tpl
    title: Kubernetes Definition
spec:
  owner: group:operations-engineering
  type: application
  lifecycle: production
  system: system:ops-eng-reports
  dependsOn:
  - component:ops-eng-reports-database
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ops-eng-reports-database
  title: Operations Engineering Reports Database
  description: DynamoDB Database for Operations Engineering Reports
spec:
  owner: group:operations-engineering
  type: database
  lifecycle: production
  system: system:ops-eng-reports
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ops-eng-reports-api
  title: Operations Engineering Reports API
  description: API for Operations Engineering Reports
spec:
  owner: group:operations-engineering
  type: API
  lifecycle: production
  system: system:ops-eng-reports
  dependsOn:
  - component:ops-eng-reports-database
  - component:ops-eng-reports-frontend
  providesApis:
  - api:ops-eng-reports-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ops-eng-reports-api
  title: Operations Engineering Reports API
  description: API for Operations Engineering Reports
spec:
  owner: group:operations-engineering
  type: openapi
  lifecycle: production
  system: system:ops-eng-reports
  definition: |
    openapi: "3.0.3"
    servers:
      - url: https://operations-engineering-reports.cloud-platform.service.justice.gov.uk
    info:
      version: 1.0.0
      title: Reports API
      license:
        name: MIT
    paths:
      /github_collaborators:
        get:
          summary: Get all undocumented External GitHub Collaborators
          description: Return undocumented External GitHub Collaborators in the MoJ GitHub Org
          responses:
            '200':
              content:
                application/javascript:
                  schema:
                    $ref: "#/components/schemas/ExternalCollabs"
              description: A JSON array of External GitHub Collaborators
            default:
              content:
                application/javascript:
                  schema:
                    $ref: "#/components/schemas/Error"
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
              description: Unexpected error
        post:
          summary: Push new External GitHub Collaborators data
          description: External GitHub Collaborators data
          requestBody:
            content:
              application/json:
                schema:
                    $ref: '#/components/schemas/ExternalCollabs'
          responses:
            '200':
              description: Data has been successfully collected
            default:
              content:
                application/javascript:
                  schema:
                    $ref: "#/components/schemas/Error"
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
              description: Unexpected error
      /github_repositories:
        get:
          summary: Get all Public Ministry of Justice Repositories and their compliance information
          description: Get all Public Ministry of Justice Repositories and their compliance information
          responses:
            '200':
              description: A JSON array of Public GitHub Repositories
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Repositories'
            default:
              content:
                application/javascript:
                  schema:
                    $ref: "#/components/schemas/Error"
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
              description: Unexpected error
        post:
          summary: Push new Ministry of Justice Repositories data
          description: Push new Ministry of Justice Repositories data
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Repositories'
          responses:
            '200':
              description: Data has been successfully collected
            default:
              content:
                application/javascript:
                  schema:
                    $ref: "#/components/schemas/Error"
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
              description: Unexpected error
    components:
      schemas:
        Error:
          properties:
            code:
              format: integer
              type: integer
            message:
              type: string
          type: object
        ExternalCollab:
          properties:
            repository:
              type: string
              description: Repository the User is attached to
            repo_url:
              type: string
              description: URL of the Repository
            login:
              type: string
              description: GitHub Username
            login_url:
              type: string
              description: Login URL for the User
            issues:
              type: array
              description: The reasons the user has been flagged as undocumented
              items:
                type: string
            href:
              type: string
            permission:
              type: string
              description: The permissions the User has for the target Repository
            last_commit:
              type: string
              description: Last commit message for the User
        ExternalCollabs:
          type: array
          description: Array of External Collaborators
          items:
            $ref: "#/components/schemas/ExternalCollab"
        Repository:
          properties:
            name:
              type: string
              description: Name of the Repository
            default_branch:
              type: string
              description: Default branch of the Repository
            status:
              type: string
              description: Compliance status of the Repository
            url:
              type: string
              description: URL of the Repository
            last_push:
              type: string
              description: Datetime of the last commit for the Repository
            report:
              type: string
            issues_enabled:
              type: string
              description: If issues are enabled on the Repository
        Repositories:
          type: array
          description: Array of Repositories
          items:
            $ref: "#/components/schemas/Repository"
      securitySchemes:
        api_key:
          type: apiKey
          name: X-API-KEY
          in: header
    security:
      - api_key: []