apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operations-engineering-reports.fullname" . }}
  labels:
    {{- include "operations-engineering-reports.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "operations-engineering-reports.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "operations-engineering-reports.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: operations-engineering-reports
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # The secrets for these environment variables are stored in the
            # cloud-platform-environment terraform state file. Accessed via the namespace.
            - name: FLASK_DEBUG
              value: {{ .Values.application.flaskDebug | quote }}
            - name: DYNAMODB_REGION
              value: "eu-west-2"
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: opseng-reports-table
                  key: table_name
            - name: AUTH0_DOMAIN
              value: {{ .Values.application.auth0Domain | quote }}
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.application.auth0ClientId | quote }}
            - name: AUTH0_CLIENT_SECRET
              value: {{ .Values.application.auth0ClientSecret | quote }}
            - name: APP_SECRET_KEY
              value: {{ .Values.application.appSecretKey | quote }}
            - name: ENCRYPTION_KEY
              value: {{ .Values.application.encryptionKey | quote }}
            - name: API_KEY
              value: {{ .Values.application.apiKey | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
