apiVersion: v1
kind: Service
metadata:
  name: {{ include "operations-engineering-reports.fullname" . }}
  labels:
    {{- include "operations-engineering-reports.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4567
      name: https
  selector:
    {{- include "operations-engineering-reports.selectorLabels" . | nindent 4 }}
