name: code-formatter

on:
  pull_request:
    paths-ignore:
      - 'helm/**'
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  format-code:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ministryofjustice/github-actions/code-formatter@v12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
