name: Test & Lint Python Code

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "report_app tests"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: true
          use-isort: false
          extra-pylint-options: "recursive=y"
          extra-pycodestyle-options: ""
          extra-flake8-options: "ignore=E501,W503"
          extra-black-options: ""
          extra-mypy-options: "ignore_missing_imports"
          extra-isort-options: ""
      - name: Test with pytest
        run: |
          make test
