name: Test & Lint Python Code

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint the codebase
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
